---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-redis
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-redis
spec:
  ports:
  - name: http
    port: 6379
    targetPort: http
  selector:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-redis
