---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsaid:demo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opsaid:demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opsaid:demo
subjects:
- kind: ServiceAccount
  name: demo
  namespace: biz-dev-uptime
