---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-v1
  namespace: appname
spec:
  ingressClassName: cilium
  rules:
  - host: appname.example.com
    http:
      paths:
      - backend:
          service:
            name: demo-v1
            port:
              number: 80
        path: /
        pathType: Prefix
