apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

configMapGenerator:
- name: argo-events-controller-config
  files:
  - controller-config.yaml=config/configmap/controller-config.yaml
  options:
    disableNameSuffixHash: true

replicas:
- name: controller-manager
  count: 1

resources:
- cluster/crds.yaml
- cluster/roles.yaml
- cluster/namespace.yaml
- cluster/events-webhook.yaml
- service/events-webhook.yaml
- workloads/deployments/controller-manager.yaml
- workloads/deployments/events-webhook.yaml

images:
- name: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/argo-events
  newTag: v1.9.0
