---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    # TODO；是运行在工作流的命名空间上
    # kubectl create secret generic ds-cred --from-literal=accessKey=scrape --from-literal=secretKey=testkey
    s3:
      bucket: scrape
      keyFormat: prefix/in/bucket     #optional
      endpoint: s3.example.com        #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
      insecure: false                 #omit for S3/GCS. Needed when minio runs without TLS
      accessKeySecret:                #omit if accessing via AWS IAM
        name: ds-cred
        key: accessKey
      secretKeySecret:                #omit if accessing via AWS IAM
        name: ds-cred
        key: secretKey
      useSDKCreds: false               #tells argo to use AWS SDK's default provider chain, enable for things like IRSA support

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: workflow-controller
value: 1000000
