apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
spec:
  selector:
    matchLabels:
      opsaid.net/appname: appname
  template:
    metadata:
      labels:
        opsaid.net/appname: appname
    spec:
      containers:
      - name: appname
        image: registry.example.com/appname
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: http
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: configuration
          mountPath: /etc/appname
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: appname
