---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneops-demo-v1
spec:
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opsaid.net/appname: oneops-demo-v1
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - /opt/service
        - --config
        - /opt/config/app.yaml
        env:
        - name: GRPC_KIT_PUHLIC_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: ccr.ccs.tencentyun.com/opsaid/demo
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 10081
          timeoutSeconds: 5
        name: oneops-demo-v1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz?service=demo.v1.oneops
            port: 10080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/config
          name: config-volume
        - mountPath: /opt/logs/applog
          name: applog-volume
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 99
        runAsUser: 99
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: oneops-demo-v1
      - name: applog-volume
        emptyDir: {}
