apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: biz-dev-uptime

commonLabels:
  opsaid.net/appname: oneops-demo-v1
  opsaid.net/pm2-uuid: 3264e3fe-2bce-4835-8588-99651a8ddd3b

commonAnnotations:
  opsaid.net/pm2-uuid: 3264e3fe-2bce-4835-8588-99651a8ddd3b

configMapGenerator:
- name: oneops-demo-v1
  files:
  - app.yaml=config/configmap/app.yaml
  options:
    disableNameSuffixHash: true

replicas:
- name: oneops-demo-v1
  count: 1

resources:
- service/ingresses.yaml
- service/services.yaml
- workloads/deployments/oneops-demo-v1.yaml

images:
- name: ccr.ccs.tencentyun.com/opsaid/demo
  newTag: 0.1.0
