---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: open-webui
      app.kubernetes.io/component: open-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-webui
        app.kubernetes.io/instance: open-webui
        app.kubernetes.io/component: open-webui
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      serviceAccountName: open-webui-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - envFrom:
        - configMapRef:
            name: open-webui
        - secretRef:
            name: open-webui
        image: ghcr.io/open-webui/open-webui
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
        name: open-webui
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /health/db
            port: http
          periodSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        tty: true
        volumeMounts:
        - mountPath: /app/backend/data
          name: data
      volumes:
      - emptyDir: {}
        name: data
